Owned-Admins Query Addition
knavesec/Max pull request #18
Opened 2021-09-08 20:38 UTC by vexance

++ owned-admins query which returns a list of all computers owned users are admins to either directly  or through unrolled group membership. I find it useful for quick wins / movement that might get missed within Bloodhound's GUI if they aren't included within shortest paths. This can probably be improved by narrowing the results down to distinct computer names to clean up output.
++ Example of owned-admins output within wiki/get-info.md
++ Grammar fix because I'm annoying
++ Option to store neo4j creds in environment variables so they aren't hard-coded. NEO4J_USERNAME can easily be put into a .bashrc or similar since it isn't really sensitive, NEO4J_PASSWORD can be exported within whichever shell / tab max will be run in. Bonus if using a space before export keyword so the command isn't recorded in history. Defaults still remain neo4j / bloodhound

2021-09-09 22:35 UTC, knavesec requested changes
Plz add the comment about auth via env variables to the overall readme as well. All else looks good!

2021-09-09 22:35 UTC, knavesec commented on max.py
> +        query = queries.get("ownedadmins", {}).get("query", "")
match the format of other commands for consistency

2021-09-09 22:35 UTC, knavesec commented on max.py
> +        cols = queries.get("ownedadmins", {}).get("columns", [""])
match the format of other commands for consistency

2021-09-10 13:34 UTC, vexance commented on max.py
> +        cols = queries.get("ownedadmins", {}).get("columns", [""])
This should now be reflected in the last two commits

2021-09-10 13:35 UTC, vexance commented on max.py
> +        query = queries.get("ownedadmins", {}).get("query", "")
Reflected in the latest two commits

2021-09-10 13:37 UTC, vexance commented
Readme has been updated with some verbiage regarding credentials as env variables and the latest query format has been updated to follow consistent styling.

2021-09-10 14:53 UTC, merged