added ADCS function
knavesec/Max pull request #44
Opened 2024-08-12 22:17 UTC by ajm4n

2024-08-12 22:18 UTC, ajm4n commented
hey dude :) added ADCS functionality

2024-08-13 00:27 UTC, skylerknecht commented on max.py
> +global_password = 'neo4jneo4j' if (not os.environ.get('NEO4J_PASSWORD', False)) else os.environ['NEO4J_PASSWORD']
is this an intentional default password change?

2024-08-13 00:46 UTC, knavesec requested changes
Awesome additions, can't wait to see this to fruition! 

I can't actually get this to work, have you field tested this? There are a few problems with the input args structure, missing functions and an infinite loop (all just off code review since I couldn't get it to work). Let comments in line, if you can get some of it working this would be sweet!

2024-08-13 00:46 UTC, knavesec commented on max.py
> +global_password = 'neo4jneo4j' if (not os.environ.get('NEO4J_PASSWORD', False)) else os.environ['NEO4J_PASSWORD']
Change this back, just want to keep it constant

2024-08-13 00:46 UTC, knavesec commented on max.py
> +    parser.add_argument('--adcs', help='Specify the AD CS query to run (adcs-CAs, adcs-enabled-certs, adcs-all-certs, adcs-enrollment-rights, adcs-rights-ca, adcs-misconfigured-certs-esc1, adcs-short
This is a pretty rough way of doing arg parsing, I get why you did it but change it to match form of the above. Add a subparser to the switch class on 1511 (on my version), then add a mutex group to parse all these out

2024-08-13 00:46 UTC, knavesec commented on max.py
> +            run_predefined_queries({ args.adcs: { "query": query, "columns": cols } })
This `run_predefined_queries` function does not exist in this context, am I missing something?

2024-08-13 00:46 UTC, knavesec commented on max.py
> +    if args.adcs in get_adcs(queries):
Within the function `get_adcs(args)` you then call `get_adcs(queries)`. Not only are these different input types, but this will just result in an infinite loop

2024-08-13 00:46 UTC, knavesec commented on max.py
> +    elif args.command == "adcs":
tbh I don't think this works with your input setup, you never actually set `args.command` equal to `adcs` so it never reaches this function

2024-08-13 00:49 UTC, knavesec commented
Oh one more, I'm fairly certain all ADCS node types are `CertTemplate` rather than `GPO`, so not sure if these queries are correct

2024-09-15 21:55 UTC, closed without merging