Stale accounts
knavesec/Max pull request #46
Opened 2024-09-18 17:58 UTC by TheToddLuci0

Mostly used for audit / reporting, but hey, maybe it'll be useful

2025-01-16 20:25 UTC, knavesec requested changes

2025-01-16 20:25 UTC, knavesec commented on max.py
> +        print("IM IN THE RIGHT PLACE")
lmao, please remove and I'll approve it

2025-01-16 20:25 UTC, knavesec commented on max.py
> +            "query" : "WITH datetime().epochseconds - (90 * 86400) AS threshold MATCH (u:User {enabled:TRUE}) WHERE u.lastlogon < threshold RETURN u.name",
Compare against last logon replicated as well

2025-01-17 16:49 UTC, TheToddLuci0 commented on max.py
> +        print("IM IN THE RIGHT PLACE")
That was just me testing if you actually reviewed things. Yep. I would never miss a debug statement. Nope.

2025-01-17 16:53 UTC, knavesec commented on max.py
> +        print("IM IN THE RIGHT PLACE")
here1 here2 here3 here4 is prime SWE

2025-01-17 16:54 UTC, knavesec commented on max.py
> +        cols = queries['staleaccounts']['columns']
Criminal that you switch between single and double, failed Open Source Coding Standards documentation

2025-01-17 17:52 UTC, knavesec requested changes

2025-01-17 17:52 UTC, knavesec commented on max.py
> +            "query" : "WITH datetime().epochseconds - (90 * 86400) AS threshold MATCH (u:User {enabled:TRUE}) WHERE u.lastlogon < threshold OR u.lastlogontimestamp < threshold RETURN u.name",
This should be AND right, since you're checking to make sure both logon timestamps are old? If the non-replicated one resolves true but the replicated one was recent, it was respond as stale

2025-01-17 17:52 UTC, knavesec commented on max.py
> +    getinfo_switch.add_argument("--stale-accounts", dest="staleaccounts",default=False,action="store_true",help="Return a list of all accounts that are enable but have not logged in within 90 days")
Also feature request, thoughts on adding similar functionality for computers that haven't been logged into in 90 days?

2025-01-17 19:16 UTC, TheToddLuci0 commented on max.py
> +            "query" : "WITH datetime().epochseconds - (90 * 86400) AS threshold MATCH (u:User {enabled:TRUE}) WHERE u.lastlogon < threshold OR u.lastlogontimestamp < threshold RETURN u.name",
Yep, good catch. It boggles the mind why MS doesn't replicate lastlogon

2025-01-29 22:03 UTC, merged